
name: US Market Morning (KST)

on:
  schedule:
    # GitHub Actions cron은 UTC 기준입니다.
    # 23:10 UTC = 08:10 KST(+9)
    - cron: "10 23 * * *"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report (US market)
        run: |
          python scripts/fetch_us_market.py

      - name: Upload artifact (site/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Notify via Telegram (optional)
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PAGES_URL: ${{ steps.deployment.outputs.page_url || 'https://hjson2.github.io/us_market_morning/' }}
        run: |
          if [ -n "$BOT_TOKEN" ] && [ -n "$CHAT_ID" ]; then
            TEXT="✅ US 마감 리포트 업데이트\r\n $PAGES_URL"
            curl -s "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
              -d "chat_id=${CHAT_ID}" \
              -d "text=${TEXT}" \
              -d "disable_web_page_preview=true" > /dev/null
          else
            echo "Telegram secrets not set. Skipping notification."
          fi
